In [1]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go # or plotly.express as px
import plotly.express as px
import dash
import dash_core_components as dcc
import dash_html_components as html

In [18]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go # or plotly.express as px
fig = go.Figure() # or any Plotly Express function e.g. px.bar(...)
# fig.add_trace( ... )
# fig.update_layout( ... )

import plotly.express as px

fig2 = px.choropleth(locations=["CHN", "USA", "IND",'LMY','EAP'], color=[1,2,3,4,5])


import dash
import dash_core_components as dcc
import dash_html_components as html

df = pd.read_csv('https://gist.githubusercontent.com/chriddyp/c78bf172206ce24f77d6363a2d754b59/raw/c353e8ef842413cae56ae3920b8fd78468aa4cb2/usa-agricultural-exports-2011.csv')


def generate_table(dataframe, max_rows=10):
    return html.Table([
        html.Thead(
            html.Tr([html.Th(col) for col in dataframe.columns])
        ),
        html.Tbody([
            html.Tr([
                html.Td(dataframe.iloc[i][col]) for col in dataframe.columns
            ]) for i in range(min(len(dataframe), max_rows))
        ])
    ])
def print_list(l):
    return html.Table([
            html.Tr([html.Td(l[i]) for i in range(len(l))])
    ])
current_list = list(['temp'])
app = dash.Dash()
app.layout = html.Div([
    dcc.Graph(figure=fig),
    html.H4(children='US Agriculture Exports (2011)'),
    generate_table(df),
    dcc.Graph(figure= fig2),
    print_list(current_list)
    
])
def modify_list(pt):
    current_list.append(pt.points)
    
app.run_server(debug=True, use_reloader=False,port = 8800)  # Turn off reloader if inside Jupyter

Running on http://127.0.0.1:8800/
Running on http://127.0.0.1:8800/
Running on http://127.0.0.1:8800/
Running on http://127.0.0.1:8800/
Running on http://127.0.0.1:8800/
Running on http://127.0.0.1:8800/
Running on http://127.0.0.1:8800/
Running on http://127.0.0.1:8800/
Running on http://127.0.0.1:8800/
Running on http://127.0.0.1:8800/
Running on http://127.0.0.1:8800/
Running on http://127.0.0.1:8800/
Running on http://127.0.0.1:8800/
Running on http://127.0.0.1:8800/
Running on http://127.0.0.1:8800/
Debugger PIN: 321-902-923
Debugger PIN: 321-902-923
Debugger PIN: 321-902-923
Debugger PIN: 321-902-923
Debugger PIN: 321-902-923
Debugger PIN: 321-902-923
Debugger PIN: 321-902-923
Debugger PIN: 321-902-923
Debugger PIN: 321-902-923
Debugger PIN: 321-902-923
Debugger PIN: 321-902-923
Debugger PIN: 321-902-923
Debugger PIN: 321-902-923
Debugger PIN: 321-902-923
Debugger PIN: 321-902-923
 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on

In [ ]:
import dash
import dash_core_components as dcc
import dash_html_components as html
import pandas as pd

df = pd.read_csv('https://gist.githubusercontent.com/chriddyp/c78bf172206ce24f77d6363a2d754b59/raw/c353e8ef842413cae56ae3920b8fd78468aa4cb2/usa-agricultural-exports-2011.csv')


def generate_table(dataframe, max_rows=10):
    return html.Table([
        html.Thead(
            html.Tr([html.Th(col) for col in dataframe.columns])
        ),
        html.Tbody([
            html.Tr([
                html.Td(dataframe.iloc[i][col]) for col in dataframe.columns
            ]) for i in range(min(len(dataframe), max_rows))
        ])
    ])


external_stylesheets = ['assets/bWLwgP.css']

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

app.layout = html.Div(children=[
    html.H4(children='US Agriculture Exports (2011)'),
    generate_table(df)
])
app.run_server(debug=True, use_reloader=False)  # Turn off reloader if inside Jupyter

In [1]:
import dash
import dash_core_components as dcc
import dash_html_components as html

external_stylesheets = [
    'assets/bWLwgP.css',
#     'assets/index.css',
]
df = pd.read_csv('https://gist.githubusercontent.com/chriddyp/c78bf172206ce24f77d6363a2d754b59/raw/c353e8ef842413cae56ae3920b8fd78468aa4cb2/usa-agricultural-exports-2011.csv')
def generate_table(dataframe, max_rows=10):
    return html.Table([
        html.Thead(
            html.Tr([html.Th(col) for col in dataframe.columns])
        ),
        html.Tbody([
            html.Tr([
                html.Td(dataframe.iloc[i][col]) for col in dataframe.columns
            ]) for i in range(min(len(dataframe), max_rows))
        ])
    ])


app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

side_elements = html.Div(children=[
    html.Label('Data'),
    generate_table(df)
])

main_space = html.Div(children = [
    html.Label('Dropdown'),
    dcc.Dropdown(
        options=[
            {'label': 'New York City', 'value': 'NYC'},
            {'label': u'Montréal', 'value': 'MTL'},
            {'label': 'San Francisco', 'value': 'SF'}
        ],
        value='MTL'
    ),

    html.Label('Multi-Select Dropdown'),
    dcc.Dropdown(
        options=[
            {'label': 'New York City', 'value': 'NYC'},
            {'label': u'Montréal', 'value': 'MTL'},
            {'label': 'San Francisco', 'value': 'SF'}
        ],
        value=['MTL', 'SF'],
        multi=True
    ),

    html.Label('Radio Items'),
    dcc.RadioItems(
        options=[
            {'label': 'New York City', 'value': 'NYC'},
            {'label': u'Montréal', 'value': 'MTL'},
            {'label': 'San Francisco', 'value': 'SF'}
        ],
        value='MTL'
    ),

    html.Label('Checkboxes'),
    dcc.Checklist(
        options=[
            {'label': 'New York City', 'value': 'NYC'},
            {'label': u'Montréal', 'value': 'MTL'},
            {'label': 'San Francisco', 'value': 'SF'}
        ],
        value=['MTL', 'SF']
    ),

    html.Label('Text Input'),
    dcc.Input(value='MTL', type='text'),

    html.Label('Slider'),
    dcc.Slider(
        min=0,
        max=9,
        marks={i: 'Label {}'.format(i) if i == 1 else str(i) for i in range(1, 6)},
        value=5,
    ),
], style={'columnCount': 2})

app.layout = html.Div(className="row",children=[
    html.Div(className="col-lg-2 left-panel",children=[side_elements]),
    html.Div(className="col-lg-10",children=[
        main_space
    ])
])


if __name__ == '__main__':
    app.run_server(debug=True,use_reloader = False)

NameError: name 'pd' is not defined

In [2]:
px.data.gapminder().head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4

In [4]:
import plotly.express as px
df = px.data.gapminder().query("year == 2007").query("continent == 'Europe'")
df.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
83,Austria,Europe,2007,79.829,8199783,36126.492700,AUT,40
119,Belgium,Europe,2007,79.441,10392226,33692.605080,BEL,56
155,Bosnia and Herzegovina,Europe,2007,74.852,4552198,7446.298803,BIH,70
191,Bulgaria,Europe,2007,73.005,7322858,10680.792820,BGR,100